version: '3.8' 
services: 
  web: 
    build: ./web 
    ports: 
      - "8080:80" 
    depends_on: 
      - db 
 
  db: 
    build: ./db 
    volumes: 
      - db_data:/var/lib/mysql 
 
volumes: 
  db_data: 
