name: Build and Push Docker Images

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Web Image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/assignment3-web:latest ./web
          docker push ghcr.io/${{ github.repository_owner }}/assignment3-web:latest

      - name: Build and Push DB Image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/assignment3-db:latest ./db
          docker push ghcr.io/${{ github.repository_owner }}/assignment3-db:latest
